Feature/login final
Liv-new-rizon/squad-3-reforca-o-bem-api pull request #1
Opened 2024-10-17 22:23 UTC by Pedrohsantosg

@samuelcamilocosta @Zord0m

2024-10-18 15:29 UTC, samuelcamilocosta requested changes

2024-10-18 15:29 UTC, samuelcamilocosta commented on src/controller/AuthController.ts
> +export const throwCustomError = (
Aqui você está exportando o erro, porém ele só é utilizado internamente no arquivo.
Se for utilizar externamente, recomendo criar uma pasta separada para deixar os tratamentos de erros desse tipo ou até mesmo um arquivo de util para ele.

2024-10-18 15:29 UTC, samuelcamilocosta commented on src/controller/AuthController.ts
> +     * Função de login do usuário.
faltou documentar os parâmetros e retorno da função

2024-10-18 15:29 UTC, samuelcamilocosta commented on src/controller/AuthController.ts
> +// Controlador de autenticação
podes trocar esse comentário pelo TSDoc da classe, TSDoc também pode ser utilizado para documentar classes, mesmo que seja mantendo só a descrição dela

2024-10-18 15:29 UTC, samuelcamilocosta commented on src/controller/UserController.ts
> +            const existingUser = await UserRepository.findOne({
É fundamental levar essa função de busca pelo email no UserRepository de repositories

2024-10-18 15:29 UTC, samuelcamilocosta commented on src/controller/UserController.ts
> +                token
não iria remover o token do momento da criação do usuário?

2024-10-18 15:29 UTC, samuelcamilocosta commented on src/library/bcrypt.ts
> +/**
O código ficará mais legível se encapsular essas funções em uma classe para utilizá-las no local.
Hoje está assim o código
```const isMatch = await comparePassword(password, user.password);```

Com uma criação da classe aqui, o código ficaria assim
```const isMatch = await NomeDadoAClasse.comparePassword(password, user.password);```

facilita na leitura do código, entender de que local vem a função utilizada.

2024-10-18 15:29 UTC, samuelcamilocosta commented on src/models/Users.ts
> +        return bcrypt.compare(candidatePassword, this.password);
faltou utilizar as funções criadas no library aqui

2024-10-18 15:29 UTC, samuelcamilocosta commented on src/models/Users.ts
> +            this.password = await bcrypt.hash(this.password, salt);
faltou utilizar as funções criadas no library aqui

2024-10-18 15:29 UTC, samuelcamilocosta commented on src/services/AuthService.ts
> +        const user = await userRepository.findOneBy({ email });
assim que criar a função de busca de um usuário por e-mail no UserRepository, aqui também conseguirá aproveitar a mesma função.

2024-10-18 15:29 UTC, samuelcamilocosta commented on src/services/AuthService.ts
> +     * Função para login do usuário.
faltou documentar os parâmetros da função e o retorno do usuário

2024-10-18 15:29 UTC, samuelcamilocosta commented on src/library/jwt.ts
> +
É importante também por padronização e para identificação, também criar uma classe para o Jwt aqui

2024-10-18 21:35 UTC, Zord0m commented
@samuelcamilocosta fiz as alterações consegue ver elas nesse PR mesmo?

2024-10-18 21:47 UTC, samuelcamilocosta commented on src/repositories/UserRepository.ts
Faltou criar a classe do UserRepository e não exportar ```MongoDataSource.getMongoRepository(User);```
Pois assim deixamos todas as partes de inserção de dados, alteração, criação, busca aqui dentro do repositório e não externamente

2024-10-19 16:14 UTC, samuelcamilocosta approved these changes

2024-10-19 16:14 UTC, merged