Criação do endpoit e validação do Tutor
Liv-new-rizon/squad-3-reforca-o-bem-api pull request #12
Opened 2024-11-12 02:19 UTC by Zord0m

2024-11-12 16:47 UTC, samuelcamilocosta requested changes

2024-11-12 16:47 UTC, samuelcamilocosta commented on src/controller/ProfileController.ts
> +                classEntity,
O nome classEntity da a entender que esse valor seria uma entidade de classe e não é.
Para deixar mais claro que é apenas um campo e não uma entidade, melhor refatorar para outro nome esse campo

2024-11-12 16:47 UTC, samuelcamilocosta commented on src/routes/routes.ts
> +    '/profile/student',
para alterar esse nome da rota, deve avisar agora o front-end já que o endpoint estava integrado

2024-11-12 16:47 UTC, samuelcamilocosta commented on src/models/Profile.ts
> +    // Campos específicos do aluno
nice comentário

2024-11-12 16:47 UTC, samuelcamilocosta commented on src/models/Profile.ts
> +    // Campos específicos do tutor
nice comentário

2024-11-12 16:47 UTC, samuelcamilocosta commented on src/utils/validation.ts
> +    const validSubjects = [
"Don't Repeat Yourself"  [(DRY)](https://medium.com/@curiousraj/the-principles-of-clean-code-dry-kiss-and-yagni-f973aa95fc4d)
Linha 64 e linha 147 possuem a mesma lógica, mesmo itens e mesmo tipo de validação, dá para refatorar isso aqui

2024-11-12 21:20 UTC, Zord0m commented on src/routes/routes.ts
> +    '/profile/student',
sera avisado

2024-11-14 19:49 UTC, samuelcamilocosta commented
falta só resolver os conflitos para poder mergear

2024-11-14 19:50 UTC, samuelcamilocosta approved these changes

2024-11-14 20:01 UTC, merged