feat(api): adiciona e atualiza endpoints para Profile e User
Liv-new-rizon/squad-3-reforca-o-bem-api pull request #3
Opened 2024-10-27 02:20 UTC by Zord0m

- Atualiza swagger com novas definições de API
- Adiciona ProfileController para gerenciamento de perfis
- Melhora integração entre UserController e ProfileController
- Adiciona novas rotas para gerenciamento de perfis

2024-10-28 17:02 UTC, samuelcamilocosta requested changes

2024-10-28 17:02 UTC, samuelcamilocosta commented on src/controller/ProfileController.ts
> +export class StudentController {
o nome do arquivo ficou como ProfileController, mas o nome da classe ficou como StudentController?
A ideia de criar um ProfileController é para que por meio dele, possamos cadastrar estudantes e professores, mesmo que na sprint de agora só estejamos falando sobre estudantes, pode já deixar o caminho preparado para isso

2024-10-28 19:40 UTC, Zord0m commented on src/controller/ProfileController.ts
> +export class StudentController {
Alterado!

2024-11-01 17:16 UTC, samuelcamilocosta commented
Branch desatualizada

2024-11-01 17:16 UTC, closed without merging